stages:
  - build
  - test
  - reload

build:
  stage: build
  script:
    - echo "test build"

docker-build:
  stage: build
  needs: ["build"]
  script:
    - echo "test docker build container"

unit-tests:
  stage: test
  needs: ["docker-build"]
  script:
    - echo "unit test is testing"

load-tests:
  stage: test
  needs: ["docker-build"]
  script:
    - echo "load tests is testing"

reload:
  stage: reload
  needs: ["load-tests", "unit-tests"]
  script:
    - echo "reload is test"